##
# Pre-commit is a multi-language package manager for pre-commit hooks.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(poetry\.lock|src/moss/store/migrations)$
repos:
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.24
  hooks:
  - id: validate-pyproject
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # If you must commit large files to git, use git-lfs according to
  # https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-submodules
  - id: trailing-whitespace
# autoflake before black and isort
# to avoid having to run pre-commit twice
- repo: https://github.com/PyCQA/autoflake
  rev: v2.3.1
  hooks:
  - id: autoflake
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.1.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
    args:
    - --py313-plus  # Adjust this for the highest version your project needs.
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args:
    - --autofix
  - id: pretty-format-yaml
    args:
    - --autofix
