# Generated by Django 5.1.7 on 2025-03-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="size",
        ),
    ]
