# Generated by Django 5.1.7 on 2025-03-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_file_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="s3_key",
        ),
    ]
